"""
Defensive k6 Summary JSON Parser
Reads summary.json generated by k6 and outputs performance metrics
to both console and GITHUB_STEP_SUMMARY markdown.
"""
import json
import os
import sys


def get_metric_value(metric_obj, key):
    """
    Defensively extract a metric value from k6's JSON output.
    k6 may output metrics in nested format (metric.values.key)
    or flat format (metric.key) depending on version and request status.
    """
    if metric_obj is None:
        return 0

    # Try nested: metric_obj['values'][key]
    if isinstance(metric_obj, dict):
        values = metric_obj.get('values', None)
        if isinstance(values, dict) and key in values:
            return values[key]
        # Try flat: metric_obj[key]
        if key in metric_obj:
            return metric_obj[key]

    return 0


def parse_summary(summary_path):
    """Parse k6 summary.json and extract key performance metrics."""
    with open(summary_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    metrics = data.get('metrics', data)

    # Extract HTTP request metrics
    http_reqs = metrics.get('http_reqs', {})
    http_req_duration = metrics.get('http_req_duration', {})
    http_req_failed = metrics.get('http_req_failed', {})
    checks = metrics.get('checks', {})

    # Throughput (RPS)
    rps = get_metric_value(http_reqs, 'rate')
    total_requests = get_metric_value(http_reqs, 'count')

    # Response times
    avg_duration = get_metric_value(http_req_duration, 'avg')
    min_duration = get_metric_value(http_req_duration, 'min')
    max_duration = get_metric_value(http_req_duration, 'max')
    p95_duration = get_metric_value(http_req_duration, 'p(95)')

    # Failure rate
    failure_rate = get_metric_value(http_req_failed, 'rate')

    # Checks pass rate
    checks_rate = get_metric_value(checks, 'rate')

    return {
        'rps': round(rps, 2),
        'total_requests': int(total_requests),
        'avg_ms': round(avg_duration, 2),
        'min_ms': round(min_duration, 2),
        'max_ms': round(max_duration, 2),
        'p95_ms': round(p95_duration, 2),
        'failure_rate': round(failure_rate * 100, 2),
        'checks_pass_rate': round(checks_rate * 100, 2) if checks_rate else 0,
    }


def format_markdown(stats):
    """Format metrics into a clean markdown executive summary."""
    md = []
    md.append("# ⚡ API Load Test — Executive Performance Summary\n")
    md.append("## Test Configuration")
    md.append("| Parameter | Value |")
    md.append("| :--- | :--- |")
    md.append("| Virtual Users (VUs) | 100 |")
    md.append("| Duration | 1 minute |")
    md.append(f"| Total Requests Sent | {stats['total_requests']} |")
    md.append(f"| Throughput (RPS) | {stats['rps']} req/sec |")
    md.append("")
    md.append("## Response Time Metrics")
    md.append("| Metric | Value |")
    md.append("| :--- | :--- |")
    md.append(f"| Average Response Time | {stats['avg_ms']} ms |")
    md.append(f"| Minimum Response Time | {stats['min_ms']} ms |")
    md.append(f"| Maximum Response Time | {stats['max_ms']} ms |")
    md.append(f"| 95th Percentile (p95) | {stats['p95_ms']} ms |")
    md.append("")
    md.append("## Reliability Metrics")
    md.append("| Metric | Value | Status |")
    md.append("| :--- | :--- | :--- |")

    fail_status = "✅ PASS" if stats['failure_rate'] < 5 else "❌ FAIL"
    p95_status = "✅ PASS" if stats['p95_ms'] < 1500 else "⚠️ WARNING"

    md.append(f"| Request Failure Rate | {stats['failure_rate']}% | {fail_status} (threshold: < 5%) |")
    md.append(f"| p95 Latency Gate | {stats['p95_ms']} ms | {p95_status} (threshold: < 1500ms) |")
    md.append(f"| Assertion Checks Pass Rate | {stats['checks_pass_rate']}% | {'✅ PASS' if stats['checks_pass_rate'] > 80 else '⚠️ WARNING'} |")
    md.append("")

    return "\n".join(md)


if __name__ == "__main__":
    summary_file = os.path.join(os.path.dirname(__file__), '..', '..', 'summary.json')

    # Allow override via command line argument
    if len(sys.argv) > 1:
        summary_file = sys.argv[1]

    if not os.path.exists(summary_file):
        print(f"Error: summary.json not found at {summary_file}")
        # Write a fallback summary
        fallback_md = "# API Load Test - Summary\n\n> **WARNING**: k6 summary.json was not generated. The load test may have failed to connect to the backend.\n"
        step_summary_path = os.environ.get('GITHUB_STEP_SUMMARY', '')
        if step_summary_path:
            with open(step_summary_path, 'a', encoding='utf-8') as f:
                f.write(fallback_md)
        try:
            print(fallback_md)
        except UnicodeEncodeError:
            print("API Load Test - Summary: k6 summary.json was not generated.")
        sys.exit(0)

    stats = parse_summary(summary_file)
    markdown = format_markdown(stats)

    # Print to console
    try:
        print(markdown)
    except UnicodeEncodeError:
        # Fallback for Windows console encoding
        print(markdown.encode('ascii', 'replace').decode('ascii'))

    # Write to GITHUB_STEP_SUMMARY if available
    step_summary_path = os.environ.get('GITHUB_STEP_SUMMARY', '')
    if step_summary_path:
        with open(step_summary_path, 'a', encoding='utf-8') as f:
            f.write(markdown)
        print(f"\nStep summary written to {step_summary_path}")
