// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvlHmUso4quPf9bNoh56T1miX6iw5uvuE',
    appId: '1:410598082535:web:8e217d23367808f0bc5f42',
    messagingSenderId: '410598082535',
    projectId: 'product-analytics-c7821',
    authDomain: 'product-analytics-c7821.firebaseapp.com',
    storageBucket: 'product-analytics-c7821.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtRgui3ncXvR6QcbXWGMMS2FhWCE_KjJU',
    appId: '1:410598082535:android:29db1dda2f58c1a6bc5f42',
    messagingSenderId: '410598082535',
    projectId: 'product-analytics-c7821',
    storageBucket: 'product-analytics-c7821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU-PB8vwCiNnpl5PSoqZznj1HnUMAVqlM',
    appId: '1:410598082535:ios:61486e249a935e8dbc5f42',
    messagingSenderId: '410598082535',
    projectId: 'product-analytics-c7821',
    storageBucket: 'product-analytics-c7821.firebasestorage.app',
    iosClientId: '410598082535-3ro9se8b0jliic0tnl7vsjqa6t6o5isg.apps.googleusercontent.com',
    iosBundleId: 'com.example.productanalytics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU-PB8vwCiNnpl5PSoqZznj1HnUMAVqlM',
    appId: '1:410598082535:ios:61486e249a935e8dbc5f42',
    messagingSenderId: '410598082535',
    projectId: 'product-analytics-c7821',
    storageBucket: 'product-analytics-c7821.firebasestorage.app',
    iosClientId: '410598082535-3ro9se8b0jliic0tnl7vsjqa6t6o5isg.apps.googleusercontent.com',
    iosBundleId: 'com.example.productanalytics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvlHmUso4quPf9bNoh56T1miX6iw5uvuE',
    appId: '1:410598082535:web:72ed59d46d017049bc5f42',
    messagingSenderId: '410598082535',
    projectId: 'product-analytics-c7821',
    authDomain: 'product-analytics-c7821.firebaseapp.com',
    storageBucket: 'product-analytics-c7821.firebasestorage.app',
  );
}
