import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/semantics.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'providers/auth_provider.dart';
import 'providers/productivity_provider.dart';
import 'providers/navigation_provider.dart';
import 'theme/app_theme.dart';
import 'utils/app_router.dart';

// void overlayMain() {
//   WidgetsFlutterBinding.ensureInitialized();
//   runApp(const MaterialApp(
//     debugShowCheckedModeBanner: false,
//     home: AppBlockerOverlay(),
//   ));
// }

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  if (kIsWeb) {
    SemanticsBinding.instance.ensureSemantics();
  }

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Background service removed from main to prevent boot crash
  // await BackgroundBlockerService.initializeService();

  runApp(const ProductivityApp());
}

class ProductivityApp extends StatelessWidget {
  const ProductivityApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => ProductivityProvider()),
        ChangeNotifierProvider(create: (_) => NavigationProvider()),
      ],
      child: MaterialApp(
        title: 'ProductivityAI',
        debugShowCheckedModeBanner: false,
        theme: AppTheme.lightTheme,
        darkTheme: AppTheme.darkTheme,
        themeMode: ThemeMode.light, // Can be made user-controlled
        home: const _AppEntry(),
      ),
    );
  }
}

class _AppEntry extends StatefulWidget {
  const _AppEntry();

  @override
  State<_AppEntry> createState() => _AppEntryState();
}

class _AppEntryState extends State<_AppEntry> {
  bool _showOnboarding = true;

  @override
  void initState() {
    super.initState();
    // Show onboarding only on first launch
    // In production, check SharedPreferences for 'seen_onboarding' key
    Future.delayed(const Duration(seconds: 2), () {
      if (mounted) setState(() => _showOnboarding = false);
    });

    // Start background blocker after app is stabilized
    // Future.delayed(const Duration(seconds: 5), () {
    //    BackgroundBlockerService.initializeService();
    // });
  }

  @override
  Widget build(BuildContext context) {
    if (_showOnboarding) {
      return const _SplashLoader();
    }
    return const AppRouter();
  }
}

class _SplashLoader extends StatelessWidget {
  const _SplashLoader();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        decoration: const BoxDecoration(
          gradient: LinearGradient(
            colors: [AppColors.primary, Color(0xFF9C95FF)],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
          ),
        ),
        child: Center(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: Colors.white.withOpacity(0.2),
                  borderRadius: BorderRadius.circular(24),
                ),
                child: const Icon(
                  Icons.psychology_outlined,
                  color: Colors.white,
                  size: 56,
                ),
              ),
              const SizedBox(height: 24),
              const Text(
                'ProductivityAI',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 28,
                  fontWeight: FontWeight.w700,
                ),
              ),
              const SizedBox(height: 8),
              const Text(
                'Your AI Productivity Coach',
                style: TextStyle(color: Colors.white70, fontSize: 14),
              ),
              const SizedBox(height: 48),
              const CircularProgressIndicator(
                valueColor: AlwaysStoppedAnimation(Colors.white),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
